"""
Airflow DAG: {dag_id}
Pipeline type: {pipeline_type}
Environment: {env}
Generated by: Ved DE Pipeline (Stage 4)
"""
from datetime import datetime, timedelta

from airflow import DAG
from airflow.operators.python import PythonOperator

default_args = {{
    'owner': '{owner}',
    'depends_on_past': False,
    'start_date': datetime(2024, 1, 1),
    'retries': {retries},
    'retry_delay': timedelta(minutes={retry_delay}),
}}

dag = DAG(
    '{dag_id}',
    default_args=default_args,
    description='{project_name} data pipeline — generated by Ved DE',
    schedule_interval="{schedule}",
    catchup=False,
    tags=['{project_name}', '{env}', '{pipeline_type}'],
)


def ingest_bronze(**kwargs):
    """Bronze layer — raw ingestion from source."""
    import subprocess
    result = subprocess.run(
        ['python3', 'stage1_understanding.py', '--project_name', '{project_name}',
         '--source', '{{{{ var.value.{project_name}_source }}}}',
         '--purpose', 'automated pipeline run'],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        raise RuntimeError(f'Stage 1 failed: {{result.stderr}}')


def transform_silver(**kwargs):
    """Silver layer — clean, conform, mask PII."""
    import subprocess
    result = subprocess.run(
        ['python3', 'stage3_build.py', '--project_name', '{project_name}'],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        raise RuntimeError(f'Stage 3 failed: {{result.stderr}}')


def validate_dq(**kwargs):
    """DQ validation — check scorecard against thresholds."""
    import json
    import os
    dq_path = os.path.join(
        os.environ.get('DE_ARTIFACTS_BASE', '/home/node/Music/de-artifacts'),
        '{project_name}', 'stage3', 'dq_scorecard.json'
    )
    with open(dq_path) as f:
        scorecard = json.load(f)
    dq_threshold = int(os.environ.get('DQ_THRESHOLD', '0'))
    score = scorecard.get('dq_score_pct', 100)
    if score < dq_threshold:
        raise ValueError(f'DQ score {{score}}% is below threshold {{dq_threshold}}%')


task_bronze = PythonOperator(
    task_id='ingest_bronze',
    python_callable=ingest_bronze,
    dag=dag,
)

task_silver = PythonOperator(
    task_id='transform_silver',
    python_callable=transform_silver,
    dag=dag,
)

task_dq = PythonOperator(
    task_id='validate_dq',
    python_callable=validate_dq,
    dag=dag,
)

task_bronze >> task_silver >> task_dq
